
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;


CREATE TABLE customers (
    customer_id VARCHAR(50) PRIMARY KEY,
    country VARCHAR(100)
);


CREATE TABLE products (
    stock_code VARCHAR(50) PRIMARY KEY,
    description TEXT
);


CREATE TABLE transactions (
    invoice_no VARCHAR(50),
    stock_code VARCHAR(50),
    quantity INTEGER,
    invoice_date TIMESTAMP,
    unit_price NUMERIC(10, 2),
    customer_id VARCHAR(50),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (stock_code) REFERENCES products(stock_code)
);

CREATE TABLE staging_retail (
    invoice_no VARCHAR(50),
    stock_code VARCHAR(50),
    description TEXT,
    quantity VARCHAR(50),
    invoice_date VARCHAR(50),
    unit_price VARCHAR(50),
    customer_id VARCHAR(50),
    country VARCHAR(100)
);

SELECT COUNT(*) FROM staging_retail;

SELECT * FROM staging_retail LIMIT 5;

-- Fix for Customers Insertion (Handles duplicate IDs cleanly)
INSERT INTO customers (customer_id, country)
SELECT 
    TRIM(customer_id), 
    MIN(country) -- Picks one consistent country if there's a variation
FROM staging_retail
WHERE customer_id IS NOT NULL 
  AND TRIM(customer_id) <> ''
GROUP BY TRIM(customer_id)
ON CONFLICT (customer_id) DO NOTHING;

-- 2. Insert unique products
INSERT INTO products (stock_code, description)
SELECT DISTINCT stock_code, MAX(description)
FROM staging_retail
WHERE stock_code IS NOT NULL AND stock_code <> ''
GROUP BY stock_code;

-- 3. Insert valid transactions (ignoring returns/negative quantities and missing customer IDs)
INSERT INTO transactions (invoice_no, stock_code, quantity, invoice_date, unit_price, customer_id)
SELECT 
    invoice_no,
    stock_code,
    CAST(quantity AS INTEGER),
    TO_TIMESTAMP(invoice_date, 'MM/DD/YYYY HH24:MI'), 
    CAST(unit_price AS NUMERIC(10,2)),
    customer_id
FROM staging_retail
WHERE customer_id IS NOT NULL 
  AND customer_id <> ''
  AND CAST(quantity AS INTEGER) > 0;

  -- Create an RFM analytical view or table
DROP TABLE IF EXISTS customer_rfm;

CREATE TABLE customer_rfm AS
SELECT 
    c.customer_id,
    c.country,
    -- Recency: Days since last purchase relative to Dec 10, 2011
    EXTRACT(DAY FROM ('2011-12-10 00:00:00'::timestamp - MAX(t.invoice_date))) AS recency,
    -- Frequency: Total number of unique invoices/orders
    COUNT(DISTINCT t.invoice_no) AS frequency,
    -- Monetary: Total revenue generated by the customer
    SUM(t.quantity * t.unit_price) AS monetary
FROM customers c
JOIN transactions t ON c.customer_id = t.customer_id
GROUP BY c.customer_id, c.country;

-- Quick check of your RFM table output
SELECT * FROM customer_rfm ORDER BY monetary DESC LIMIT 10;
